# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-07-25 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='业务线')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=16, verbose_name='槽位')),
                ('pd_type', models.CharField(max_length=16, verbose_name='类型')),
                ('capacity', models.CharField(max_length=64, verbose_name='容量')),
                ('model', models.CharField(max_length=64, verbose_name='型号')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=32, verbose_name='容量')),
                ('slot', models.CharField(max_length=32, verbose_name='插槽位')),
                ('model', models.CharField(max_length=32, verbose_name='型号')),
                ('speed', models.CharField(max_length=32, verbose_name='速度')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='制造商')),
                ('sn', models.CharField(max_length=32, verbose_name='内存SN号')),
            ],
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=128, verbose_name='网卡名称')),
                ('address', models.CharField(max_length=32, verbose_name='ip地址')),
                ('netmask', models.CharField(max_length=32, verbose_name='子网掩码')),
                ('broadcast', models.CharField(max_length=32, verbose_name='')),
                ('hwaddr', models.CharField(max_length=32, verbose_name='网卡mac地址')),
                ('up', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='最近汇报时间')),
                ('cabinet_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜号')),
                ('cabinet_order', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜中序号')),
                ('os_platform', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统版本')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='SN号')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='制造商')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('cpu_count', models.CharField(blank=True, max_length=32, null=True, verbose_name='cpu个数')),
                ('cpu_physical_count', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('cpu_model', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BusinessUnit', verbose_name='业务线')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IDC', verbose_name='机房')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='nic',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='服务器'),
        ),
        migrations.AddField(
            model_name='memory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='服务器'),
        ),
        migrations.AddField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='服务器'),
        ),
        migrations.AddField(
            model_name='assetsrecord',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='服务器'),
        ),
    ]
